services:
  - type: web
    name: annsetu-backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node server.js"
    envVars:
      - key: MONGO_URI
        value: ""
      - key: JWT_SECRET
        value: ""
